spring:
  datasource:
    url: jdbc:mysql://${domain.ip}:3306
    hikari:
      username: root
      password: ${domain.password}
      connection-init-sql: select 1
      minimum-idle: 8
      maximum-pool-size: 24
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
        useSSL: false
        serverTimezone: UTC
        allowMultiQueries: true
        autoReconnect: true
