domain:
  ip: localhost
  password: '@Wasd135139'
server:
  port: 8001
  servlet:
    context-path: /platform
spring:
  application:
    name: platform-server
  profiles:
    include:
      - mysql
      - redis
  datasource:
    hikari:
      catalog: concise-platform
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
